// comment out the one that you are not compiling

#define DONTCOMPILE 0
#define GGAME_TF2 1
#define GGAME_CSS 3
#define GGAME_ANYTF 4
#define GGAME_TRADE 5
#define GGAME_HIGHLANDER 7

#define GGAME_PVM 6 // for GGAMETYPE2
#define GGAME_TF2_NORMAL 7 // for GGAMETYPE2
#define GGAME_MVM 2 // for GGAMETYPE2

#define GGAMETYPE GGAME_TF2
#define GGAMETYPE2 GGAME_TF2_NORMAL

//meanwhile in coding...

//#if GGAMETYPE == GGAME_TF2

//actual codes

//#endif
